let currentPage = "dashboardPage";
let tripActive = false;
let tripTimer = null;
let tripStartedAt = null;

document.addEventListener("DOMContentLoaded", async () => { await openDatabase(); setupNavigation(); setupActions(); setupFuelForm(); setupNetworkStatus(); registerServiceWorker(); setDefaultDate(); loadFuelHistory(); const bootV06=()=>typeof initV06==="function"?initV06():setTimeout(bootV06,50); bootV06(); });
function setupNavigation(){document.querySelectorAll(".nav-item").forEach(button=>button.addEventListener("click",()=>showPage(button.dataset.page)));}
function showPage(pageId){document.querySelectorAll(".page").forEach(page=>page.classList.remove("active"));document.getElementById(pageId)?.classList.add("active");document.querySelectorAll(".nav-item").forEach(item=>item.classList.toggle("active",item.dataset.page===pageId));currentPage=pageId;}
function setupActions(){document.querySelectorAll('[data-action="fuel"]').forEach(button=>button.addEventListener("click",openFuelModal));document.querySelectorAll('[data-action="service"]').forEach(button=>button.addEventListener("click",()=>window.DRIVE_MAINTENANCE?.openMaintenance()));document.getElementById("startDriveButton")?.addEventListener("click",startDrive);document.getElementById("stopDriveButton")?.addEventListener("click",stopDrive);document.querySelectorAll("[data-close]").forEach(button=>button.addEventListener("click",()=>closeModal(button.dataset.close)));}
function openFuelModal(){document.getElementById("fuelModal")?.classList.remove("hidden");const input=document.getElementById("fuelOdometer");if(input)input.value=(document.getElementById("odometerValue")?.textContent||"").replaceAll(",","").replace(/[^0-9.]/g,"");input?.focus();}
function closeModal(id){document.getElementById(id)?.classList.add("hidden");}
function setDefaultDate(){const input=document.getElementById("fuelDate");if(input)input.value=new Date().toISOString().split("T")[0];}
function vehicleRecords(records,vehicleId){return records.filter(r=>!vehicleId||r.vehicleId==null||r.vehicleId===vehicleId);}
async function setupFuelForm(){const form=document.getElementById("fuelForm");if(!form)return;form.addEventListener("submit",async event=>{event.preventDefault();const active=typeof getActiveVehicle==="function"?await getActiveVehicle():null;const odometer=Number(document.getElementById("fuelOdometer").value),litres=Number(document.getElementById("fuelLitres").value),cost=Number(document.getElementById("fuelCost").value),date=document.getElementById("fuelDate").value;if(odometer<=0||litres<=0||cost<0)return;const records=vehicleRecords(await getAllRecords("fuel"),active?.id).sort((a,b)=>Number(b.odometer||0)-Number(a.odometer||0));const previous=records.find(r=>Number(r.odometer)<odometer)||records[0]||null;const distance=previous&&odometer>Number(previous.odometer)?odometer-Number(previous.odometer):null;await addRecord("fuel",{vehicleId:active?.id,odometer,litres,cost,date,distance,economy:distance?litres/distance*100:null,costPerKm:distance?cost/distance:null,createdAt:new Date().toISOString(),synced:false});if(active&&odometer>Number(active.odometer||0)){active.odometer=odometer;await putRecord("vehicles",active);}closeModal("fuelModal");form.reset();setDefaultDate();await loadFuelHistory();if(typeof initV06==="function")await initV06();});["fuelOdometer","fuelLitres","fuelCost"].forEach(id=>document.getElementById(id)?.addEventListener("input",previewFuel));}
async function previewFuel(){const odometer=Number(document.getElementById("fuelOdometer")?.value),litres=Number(document.getElementById("fuelLitres")?.value);if(!odometer||!litres)return;const active=typeof getActiveVehicle==="function"?await getActiveVehicle():null;const previous=vehicleRecords(await getAllRecords("fuel"),active?.id).filter(r=>Number(r.odometer)<odometer).sort((a,b)=>Number(b.odometer)-Number(a.odometer))[0];if(!previous)return;const distance=odometer-Number(previous.odometer);if(distance<=0)return;document.getElementById("fuelCalculation")?.classList.remove("hidden");const output=document.getElementById("calculatedEconomy");if(output)output.textContent=(litres/distance*100).toFixed(2);}
async function loadFuelHistory(){const container=document.getElementById("fuelHistory");if(!container)return;const active=typeof getActiveVehicle==="function"?await getActiveVehicle():null;const records=vehicleRecords(await getAllRecords("fuel"),active?.id).sort((a,b)=>Number(b.odometer||0)-Number(a.odometer||0));container.innerHTML=records.slice(0,20).map(r=>`<article class="activity"><div class="activity-icon fuel">⛽</div><div class="activity-info"><strong>${Number(r.litres||0).toFixed(1)} L</strong><span>P${Number(r.cost||0).toFixed(2)} · ${Number(r.odometer||0).toLocaleString()} km</span></div><div class="activity-value">${r.economy?`${Number(r.economy).toFixed(2)} L/100`:"—"}</div></article>`).join("");}
function startDrive(){if(!navigator.geolocation){alert("Your browser does not support GPS.");return;}tripActive=true;tripStartedAt=Date.now();GPS.start();document.getElementById("tripLiveCard")?.classList.remove("hidden");const button=document.getElementById("startDriveButton");if(button)button.textContent="DRIVING";showPage("tripsPage");tripTimer=setInterval(updateTripTimer,1000);}
async function stopDrive(){if(!tripActive)return;GPS.stop();clearInterval(tripTimer);const endedAt=Date.now();const active=typeof getActiveVehicle==="function"?await getActiveVehicle():null;const distance=Number(GPS.distance||0);await addRecord("trips",{vehicleId:active?.id,startTime:new Date(tripStartedAt).toISOString(),endTime:new Date(endedAt).toISOString(),distance,duration:endedAt-tripStartedAt,points:GPS.points,createdAt:new Date().toISOString(),synced:false});tripActive=false;document.getElementById("tripLiveCard")?.classList.add("hidden");const button=document.getElementById("startDriveButton");if(button)button.textContent="● START DRIVE";alert(`Trip saved: ${distance.toFixed(2)} km`);GPS.points=[];GPS.distance=0;if(typeof initV06==="function")await initV06();}
function updateTripTimer(){if(!tripStartedAt)return;const seconds=Math.floor((Date.now()-tripStartedAt)/1000),minutes=Math.floor(seconds/60),remaining=seconds%60;const output=document.getElementById("liveDuration");if(output)output.textContent=`${String(minutes).padStart(2,"0")}:${String(remaining).padStart(2,"0")}`;}
document.addEventListener("gpsupdate",event=>{const{point,distance}=event.detail;const d=document.getElementById("liveDistance"),a=document.getElementById("liveAccuracy");if(d)d.textContent=`${distance.toFixed(2)} km`;if(a)a.textContent=`GPS ±${Math.round(point.accuracy)} m`;});
function setupNetworkStatus(){const update=()=>{const s=document.getElementById("networkStatus"),t=document.getElementById("networkText");if(navigator.onLine)s?.classList.add("hidden");else{s?.classList.remove("hidden");if(t)t.textContent="Offline — data saved locally";}};window.addEventListener("online",update);window.addEventListener("offline",update);update();}
async function registerServiceWorker(){if(!( "serviceWorker" in navigator))return;try{const registration=await navigator.serviceWorker.register("./sw.js",{updateViaCache:"none"});document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")registration.update();});registration.addEventListener("updatefound",()=>{const worker=registration.installing;worker?.addEventListener("statechange",()=>{if(worker.state==="installed"&&navigator.serviceWorker.controller)showUpdatePrompt(worker);});});}catch(error){console.error("Service worker registration failed:",error);}}
function showUpdatePrompt(worker){document.getElementById("updateModal")?.classList.remove("hidden");const button=document.getElementById("updateButton");if(button)button.onclick=()=>{worker.postMessage({type:"SKIP_WAITING"});window.location.reload();};}
(function loadDriveModules(){const load=src=>new Promise((resolve,reject)=>{const s=document.createElement("script");s.src=`./${src}?v=0.6`;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});load("maintenance.js").then(()=>load("data-tools.js")).then(()=>load("v0.6.js")).then(()=>load("insights.js")).catch(error=>console.error("DRIVE v0.6 module load failed:",error));})();
