/* DRIVE v0.27 — Vehicle Decision Engine */
(()=>{
"use strict";
const W={attention:100,watch:70,info:35,positive:15},S={predictive:1.15,anomaly:1.1,maintenance:1.2,data:.9};
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const conf=v=>typeof v==='number'?Math.max(0,Math.min(1,v)):(v==='high'?.9:v==='medium'?.7:v==='low'?.45:.6);
const sev=v=>W[v]?v:'info';
function mount(){let h=document.getElementById('driveDecision');if(h)return h;const health=document.querySelector('#dashboardPage .panel[aria-labelledby="health-title"]');if(!health)return null;h=document.createElement('section');h.id='driveDecision';h.className='panel drive-decision';h.setAttribute('aria-labelledby','decision-title');h.innerHTML='<div class="decision-empty"><span class="decision-kicker">NEXT BEST ACTION</span><strong id="decision-title">Building your decision model</strong><p>DRIVE is combining maintenance, fuel, driving and cost signals.</p></div>';health.after(h);const st=document.createElement('style');st.textContent='.drive-decision{margin-top:18px}.decision-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.decision-kicker{display:block;color:#858c93;font-size:9px;font-weight:800;letter-spacing:.14em;margin-bottom:6px}.decision-head h2{margin:0;font-size:20px;line-height:1.2}.decision-severity{padding:5px 7px;border-radius:5px;font-size:8px;font-weight:900;letter-spacing:.1em;background:rgba(255,255,255,.05);color:#858c93}.decision-severity.attention{color:#ff5d5d;background:rgba(255,93,93,.08)}.decision-severity.watch{color:#f4c95d;background:rgba(244,201,93,.08)}.decision-severity.positive{color:#d8ff3e;background:rgba(216,255,62,.07)}.decision-message{margin:10px 0 14px;font-size:13px;line-height:1.5}.decision-action{border-left:2px solid #d8ff3e;padding:10px 12px;background:rgba(216,255,62,.035);border-radius:0 8px 8px 0}.decision-action span{display:block;color:#858c93;font-size:8px;font-weight:800;letter-spacing:.12em;margin-bottom:4px}.decision-action strong{font-size:12px;line-height:1.45}.decision-details{margin-top:12px;border-top:1px solid rgba(255,255,255,.07);padding-top:10px}.decision-details summary{cursor:pointer;color:#858c93;font-size:11px;min-height:24px;display:flex;align-items:center}.decision-details p{color:#858c93;font-size:11px;line-height:1.5}.decision-details dl{margin:0;display:grid;gap:5px}.decision-details dl div{display:flex;justify-content:space-between;gap:12px;font-size:10px}.decision-details dt{color:#858c93}.decision-details dd{margin:0}.decision-more{display:grid;gap:8px;margin-top:12px}.decision-row{display:flex;gap:9px;padding-top:9px;border-top:1px solid rgba(255,255,255,.06)}.decision-row strong{font-size:11px}.decision-row p{margin:3px 0 0;color:#858c93;font-size:11px;line-height:1.4}@media(max-width:480px){.decision-head h2{font-size:18px}.decision-message{font-size:12.5px}}';document.head.appendChild(st);return h}
function make(x){return{id:`${x.type}-${x.severity}`,priority:99,severity:sev(x.severity),type:x.type,title:x.title,message:x.message,action:x.action,why:x.why,evidence:x.evidence||{},confidence:conf(x.confidence),source:x.source||'data'}}
function canonical(t=''){t=t.toLowerCase();if(t.includes('service')||t.includes('maintenance'))return'service';if(t.includes('fuel')||t.includes('economy')||t.includes('consumption'))return'fuel';if(t.includes('cost')||t.includes('spend'))return'cost';if(t.includes('trip')||t.includes('drive')||t.includes('route')||t.includes('usage'))return'driving';return t||'vehicle'}
async function collect(){const out={decisions:[],health:null};try{const p=await window.DRIVE_PREDICTIVE?.analyse?.();(p?.insights||[]).forEach(i=>out.decisions.push(make({type:i.type||'predictive',severity:i.severity,title:i.title||'Vehicle trend',message:i.message||'A vehicle trend has been detected.',action:i.action||'Review the recorded data.',why:i.why||'Recent vehicle data shows a measurable change.',evidence:i.evidence,confidence:i.confidence,source:'predictive'})));out.health=p?.health||null}catch(e){console.warn('Decision predictive input unavailable',e)}
try{const d=await window.DRIVE_DATA?.snapshot?.();const m=await window.DRIVE_MAINTENANCE?.analyse?.();if(m?.status==='overdue')out.decisions.push(make({type:'service',severity:'attention',title:'Service is overdue',message:'A recorded service interval appears to have been reached or passed.',action:'Book or perform the required service, then record it in DRIVE.',why:'The maintenance record contains an interval that has been reached or passed.',evidence:m,confidence:.95,source:'maintenance'}));else if(m?.status==='due-soon')out.decisions.push(make({type:'service',severity:'watch',title:'Service is approaching',message:'A recorded service interval is approaching.',action:'Plan the service and keep the next interval updated in DRIVE.',why:'The stored maintenance interval is close to its threshold.',evidence:m,confidence:.9,source:'maintenance'}));const a=await window.DRIVE_ANOMALY?.analyse?.(d);(a?.signals||a?.anomalies||[]).forEach(i=>out.decisions.push(make({type:i.type||'vehicle-signal',severity:i.severity==='high'?'attention':i.severity,title:i.title||'Vehicle signal',message:i.message||'A change was detected in recorded data.',action:i.action||'Review the signal and compare it with recent records.',why:i.why||'The signal is based on historical vehicle data.',evidence:i.evidence,confidence:i.confidence,source:'anomaly'})))}catch(e){console.warn('Decision data input unavailable',e)}return out}
function rank(a){const m=new Map();a.forEach(x=>{const k=canonical(x.type),old=m.get(k);if(!old||W[x.severity]+x.confidence*10>W[old.severity]+old.confidence*10)m.set(k,x)});return[...m.values()].map(x=>({...x,score:W[x.severity]*(S[x.source]||1)+x.confidence*10})).sort((a,b)=>b.score-a.score).map((x,i)=>({...x,priority:i+1}))}
function render(r){const h=mount();if(!h)return;const a=r.decisions.slice(0,3);if(!a.length){h.innerHTML='<div class="decision-empty"><span class="decision-kicker">NEXT BEST ACTION</span><strong>Keep recording your drives</strong><p>DRIVE needs more history before it can recommend a meaningful next action.</p></div>';return}const t=a[0],rest=a.slice(1);h.innerHTML=`<div class="decision-head"><div><span class="decision-kicker">NEXT BEST ACTION</span><h2>${esc(t.title)}</h2></div><span class="decision-severity ${esc(t.severity)}">${esc(t.severity.toUpperCase())}</span></div><p class="decision-message">${esc(t.message)}</p><div class="decision-action"><span>ACTION</span><strong>${esc(t.action)}</strong></div><details class="decision-details"><summary>Why DRIVE is recommending this</summary><p>${esc(t.why)}</p><dl>${Object.entries(t.evidence).slice(0,5).map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></details>${rest.length?'<div class="decision-more">'+rest.map(x=>`<div class="decision-row"><span class="decision-severity ${esc(x.severity)}">${esc(x.severity.toUpperCase())}</span><div><strong>${esc(x.title)}</strong><p>${esc(x.message)}</p></div></div>`).join('')+'</div>':''}`}
async function refresh(){const r=await collect();r.decisions=rank(r.decisions);render(r);return r}
window.DRIVE_DECISION={collect,refresh,rank};window.addEventListener('drive:datachanged',refresh);document.addEventListener('DOMContentLoaded',()=>setTimeout(refresh,300));
})();