/* DRIVE — Vehicle Documents */
(()=>{
"use strict";
const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const match=(r,v)=>!v?.id||r.vehicleId==null||String(r.vehicleId)===String(v.id);
let objectUrls=[];
async function vehicle(){let v=await getActiveVehicle();if(!v&&typeof ensureDefaultVehicle==="function")v=await ensureDefaultVehicle();return v}
function ensureModal(){let m=document.getElementById("documentsModal");if(m)return m;m=document.createElement("div");m.id="documentsModal";m.className="modal hidden";m.setAttribute("role","dialog");m.setAttribute("aria-modal","true");m.innerHTML=`<div class="modal-sheet documents-sheet"><div class="modal-handle" aria-hidden="true"></div><div class="modal-header"><div><span class="eyebrow">VEHICLE RECORDS</span><h2>Documents</h2></div><button type="button" class="modal-close" data-doc-close aria-label="Close documents">×</button></div><form id="documentForm"><label>Document name<input id="documentName" required maxlength="120" placeholder="Registration, insurance, licence…"></label><label>Category<select id="documentCategory"><option>Registration</option><option>Insurance</option><option>Licence</option><option>Service</option><option>Warranty</option><option>Other</option></select></label><label>Document date<input id="documentDate" type="date"></label><label>Expiry date<input id="documentExpiry" type="date"></label><label>Notes<textarea id="documentNotes" rows="3" maxlength="500" placeholder="Optional notes"></textarea></label><label class="document-file-label">Attach file<input id="documentFile" type="file" accept="application/pdf,image/*,.doc,.docx,.txt" required><small id="documentFileName">PDF or image recommended · stored locally on this device</small></label><p id="documentSaveError" class="form-error" role="alert" hidden></p><button class="submit-button" type="submit">SAVE DOCUMENT</button></form><div id="documentHistory" class="tool-history"></div></div>`;document.body.appendChild(m);return m}
function injectStyles(){if(document.getElementById("drive-documents-style"))return;const s=document.createElement("style");s.id="drive-documents-style";s.textContent=`.documents-sheet{max-height:88vh;overflow:auto}.documents-sheet #documentForm{display:grid;gap:12px}.document-file-label input{margin-top:8px}.document-file-label small{display:block;margin-top:6px;color:var(--muted,#858c93);font-size:10px;line-height:1.4}.document-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center}.document-main strong{display:block;font-size:12px}.document-main small{display:block;margin-top:4px;color:var(--muted,#858c93);font-size:10px;line-height:1.4}.document-actions{display:flex;align-items:center;gap:6px}.document-actions button{border:1px solid var(--line,#303030);background:var(--surface,#151515);color:inherit;border-radius:8px;padding:7px 9px;font-size:10px}.document-expired{color:#d6868b}.document-soon{color:#d0b56c}`;document.head.appendChild(s)}
function expiryClass(date){if(!date)return "";const diff=(new Date(date+"T23:59:59")-new Date())/86400000;if(diff<0)return "document-expired";if(diff<=30)return "document-soon";return ""}
async function renderHistory(m){const list=m.querySelector("#documentHistory"),v=await vehicle(),rows=(await getAllRecords("documents")).filter(r=>match(r,v)).sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0));objectUrls.forEach(u=>URL.revokeObjectURL(u));objectUrls=[];list.innerHTML=`<div class="tool-history-title">DOCUMENT VAULT</div>`+(rows.length?rows.slice(0,30).map(r=>{const expiry=expiryClass(r.expiryDate);return `<div class="tool-history-row document-row"><div class="document-main"><strong>${esc(r.name||"Document")}</strong><small>${esc(r.category||"Other")} · ${esc(r.documentDate||"")}${r.expiryDate?` · <span class="${expiry}">expires ${esc(r.expiryDate)}</span>`:""}${r.fileName?` · ${esc(r.fileName)}`:""}</small></div><div class="document-actions">${r.fileData?`<button type="button" data-doc-view="${r.id}">OPEN</button>`:""}<button type="button" data-doc-delete="${r.id}" aria-label="Delete ${esc(r.name||"document")}">×</button></div></div>`}).join(""):"<p class=\"tool-empty\">No vehicle documents yet.</p>");list.querySelectorAll("[data-doc-view]").forEach(b=>b.onclick=()=>openDocument(Number(b.dataset.docView)));list.querySelectorAll("[data-doc-delete]").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this document?"))return;await deleteRecord("documents",Number(b.dataset.docDelete));await renderHistory(m);window.dispatchEvent(new CustomEvent("drive:datachanged",{detail:{store:"documents"}}))})}
async function openDocument(id){const r=await getRecord("documents",id);if(!r?.fileData)return;try{const bytes=Uint8Array.from(atob(r.fileData),c=>c.charCodeAt(0)),blob=new Blob([bytes],{type:r.mimeType||"application/octet-stream"}),url=URL.createObjectURL(blob);objectUrls.push(url);window.open(url,"_blank","noopener,noreferrer")}catch(e){console.error("Document open failed",e);alert("This document could not be opened.")}}
function bind(m){const form=m.querySelector("#documentForm");if(!form.dataset.bound){form.dataset.bound="1";m.querySelector("#documentFile")?.addEventListener("change",e=>{const f=e.target.files?.[0];m.querySelector("#documentFileName").textContent=f?`${f.name} · ${(f.size/1024/1024).toFixed(2)} MB · stored locally on this device`:"PDF or image recommended · stored locally on this device"});form.addEventListener("submit",save)}const close=m.querySelector("[data-doc-close]");if(close&&!close.dataset.bound){close.dataset.bound="1";close.onclick=()=>m.classList.add("hidden")}}
async function save(e){e.preventDefault();const m=ensureModal(),q=id=>m.querySelector(`#${id}`),err=q("documentSaveError"),file=q("documentFile").files?.[0],v=await vehicle();if(!v){err.textContent="Vehicle is not ready. Reload DRIVE and try again.";err.hidden=false;return}if(!file){err.textContent="Choose a document file first.";err.hidden=false;return}if(file.size>8*1024*1024){err.textContent="File is too large. Keep documents under 8 MB.";err.hidden=false;return}try{const buffer=await file.arrayBuffer(),bytes=new Uint8Array(buffer);let binary="";const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,i+chunk));const record={vehicleId:v.id,name:q("documentName").value.trim(),category:q("documentCategory").value,documentDate:q("documentDate").value||today(),expiryDate:q("documentExpiry").value||null,notes:q("documentNotes").value.trim(),fileName:file.name,mimeType:file.type||"application/octet-stream",fileSize:file.size,fileData:btoa(binary),createdAt:new Date().toISOString(),synced:false};if(!record.name){err.textContent="Enter a document name.";err.hidden=false;return}const id=await addRecord("documents",record);await renderHistory(m);e.currentTarget.reset();q("documentDate").value=today();q("documentFileName").textContent="PDF or image recommended · stored locally on this device";m.classList.add("hidden");announce?.(`Document saved: ${record.name}.`);window.dispatchEvent(new CustomEvent("drive:datachanged",{detail:{store:"documents",id}}))}catch(error){console.error(error);err.textContent="Document could not be saved. The browser may not have enough local storage.";err.hidden=false}}
async function open(){const m=ensureModal();injectStyles();bind(m);m.querySelector("#documentDate").value=today();await renderHistory(m);m.classList.remove("hidden");m.querySelector("#documentName").focus()}
async function refresh(){try{const m=ensureModal();injectStyles();await renderHistory(m)}catch(e){console.error("Documents refresh failed",e)}}
window.DRIVE_DOCUMENTS={open,refresh,renderHistory};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{ensureModal();injectStyles();refresh()},{once:true});else{ensureModal();injectStyles();refresh()}
})();
