/* DRIVE v0.38 — Live Drive Intelligence */
(function(){
  "use strict";
  const $=id=>document.getElementById(id);
  let canvas=null,ctx=null,points=[],speeds=[],listenerBound=false,resizeObserver=null,lastPoint=null;
  function styles(){if($("driveLiveMapStyles"))return;const s=document.createElement("style");s.id="driveLiveMapStyles";s.textContent=`.live-map-wrap{margin:14px 0 12px;border:1px solid rgba(255,255,255,.08);border-radius:16px;overflow:hidden;background:#0d1012;box-shadow:0 8px 24px rgba(0,0,0,.18)}.live-map-pane{position:relative;width:100%;height:190px;overflow:hidden;background:#dfe4df}.live-map-canvas{display:block;width:100%;height:190px!important}.live-map-status{position:absolute;z-index:2;top:12px;left:12px;padding:7px 10px;border:1px solid rgba(255,255,255,.55);border-radius:999px;background:rgba(255,255,255,.9);backdrop-filter:blur(10px);font-size:9px;font-weight:800;letter-spacing:.09em;color:#262626;box-shadow:0 2px 10px rgba(0,0,0,.12)}.live-telemetry{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:10px 0 0}.live-telemetry>div{padding:10px 11px;border:1px solid rgba(255,255,255,.07);border-radius:10px;background:#111417}.live-telemetry span{display:block;color:#858c93;font-size:8px;letter-spacing:.1em;font-weight:800}.live-telemetry strong{display:block;margin-top:5px;font-size:13px}@media(min-width:481px){.live-map-pane,.live-map-canvas{height:210px!important}.live-telemetry{grid-template-columns:repeat(4,1fr)}}@media(prefers-reduced-motion:reduce){.live-map-wrap *{scroll-behavior:auto!important;transition:none!important;animation:none!important}}`;
  document.head.appendChild(s)}
  function mount(){styles();const card=$("tripLiveCard");if(!card)return;let w=$("driveLiveMapWrap");if(!w){w=document.createElement("div");w.id="driveLiveMapWrap";w.className="live-map-wrap";w.innerHTML='<div class="live-map-pane"><div class="live-map-status" id="liveMapStatus">WAITING FOR GPS</div><canvas id="driveLiveMap" class="live-map-canvas" role="img" aria-label="Live drive map showing your current position and route"></canvas></div><div class="live-telemetry"><div><span>SPEED</span><strong id="liveSpeed">— KM/H</strong></div><div><span>AVG SPEED</span><strong id="liveAverageSpeed">— KM/H</strong></div><div><span>DISTANCE</span><strong id="liveMapDistance">0.00 KM</strong></div><div><span>GPS QUALITY</span><strong id="liveGpsQuality">—</strong></div></div>';const stop=$("stopDriveButton");card.insertBefore(w,stop||null)}if(canvas)return;canvas=$("driveLiveMap");if(!canvas)return;ctx=canvas.getContext("2d");resizeCanvas();resizeObserver=new ResizeObserver(resizeCanvas);resizeObserver.observe(canvas)}
  function resizeCanvas(){if(!canvas||!ctx)return;const rect=canvas.getBoundingClientRect();const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
  function project(ll,width,height){if(!points.length)return [width/2,height/2];let minLat=Math.min(...points.map(p=>p[0])),maxLat=Math.max(...points.map(p=>p[0])),minLng=Math.min(...points.map(p=>p[1])),maxLng=Math.max(...points.map(p=>p[1]));const pad=70;const latSpan=Math.max(maxLat-minLat,0.00035),lngSpan=Math.max(maxLng-minLng,0.00035);const scale=Math.min((width-pad*2)/lngSpan,(height-pad*2)/latSpan);const x=width/2+(ll[1]-(minLng+maxLng)/2)*scale;const y=height/2-(ll[0]-(minLat+maxLat)/2)*scale;return [x,y]}
  function draw(){if(!canvas||!ctx)return;const w=canvas.clientWidth||300,h=canvas.clientHeight||190;ctx.clearRect(0,0,w,h);ctx.fillStyle="#dfe4df";ctx.fillRect(0,0,w,h);ctx.strokeStyle="rgba(55,65,60,.13)";ctx.lineWidth=1;for(let x=0;x<w;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}if(!points.length){ctx.fillStyle="rgba(30,35,32,.55)";ctx.font="700 11px system-ui,sans-serif";ctx.textAlign="center";ctx.fillText("WAITING FOR GPS",w/2,h/2);return}const projected=points.map(p=>project(p,w,h));if(projected.length>1){ctx.beginPath();projected.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.strokeStyle="#111417";ctx.lineWidth=5;ctx.lineCap="round";ctx.lineJoin="round";ctx.stroke();ctx.strokeStyle="#d8ff3e";ctx.lineWidth=3;ctx.stroke()}const p=projected[projected.length-1];ctx.beginPath();ctx.arc(p[0],p[1],9,0,Math.PI*2);ctx.fillStyle="#d8ff3e";ctx.fill();ctx.lineWidth=3;ctx.strokeStyle="#111417";ctx.stroke();ctx.beginPath();ctx.arc(p[0],p[1],3,0,Math.PI*2);ctx.fillStyle="#111417";ctx.fill()}
  function quality(a){if(!Number.isFinite(a))return "WAITING";if(a<=10)return "EXCELLENT";if(a<=25)return "GOOD";if(a<=50)return "FAIR";return "WEAK"}
  function update(point,distance){mount();if(!canvas)return;lastPoint=point;points.push([point.lat,point.lng]);const speed=Number.isFinite(point.speed)&&point.speed>=0?point.speed*3.6:0;speeds.push(speed);draw();$("liveSpeed")&&($("liveSpeed").textContent=`${speed.toFixed(0)} KM/H`);$("liveAverageSpeed")&&($("liveAverageSpeed").textContent=`${(speeds.reduce((a,b)=>a+b,0)/speeds.length).toFixed(0)} KM/H`);$("liveMapDistance")&&($("liveMapDistance").textContent=`${Number(distance||0).toFixed(2)} KM`);$("liveGpsQuality")&&($("liveGpsQuality").textContent=quality(point.accuracy));$("liveMapStatus")&&($("liveMapStatus").textContent="GPS LIVE")}
  function reset(){points=[];speeds=[];lastPoint=null;draw();if($("liveMapStatus"))$("liveMapStatus").textContent="WAITING FOR GPS";if($("liveSpeed"))$("liveSpeed").textContent="— KM/H";if($("liveAverageSpeed"))$("liveAverageSpeed").textContent="— KM/H";if($("liveMapDistance"))$("liveMapDistance").textContent="0.00 KM";if($("liveGpsQuality"))$("liveGpsQuality").textContent="—"}
  function init(){styles();mount();if(!listenerBound){document.addEventListener("gpsupdate",e=>{if(window.DRIVE_APP?.isTripActive())update(e.detail.point,e.detail.distance)});window.addEventListener("drive:datachanged",()=>{if(!window.DRIVE_APP?.isTripActive())reset()});listenerBound=true}}
  window.DRIVE_LIVE_V038={init,reset};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
