/* DRIVE v0.39 — Real GPS maps + complete trip history + trip economics */
(function(){
  "use strict";
  const $=id=>document.getElementById(id);
  const money=v=>`P${Number(v||0).toFixed(2)}`;
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
  const duration=ms=>{const m=Math.max(0,Math.round(Number(ms||0)/60000)),h=Math.floor(m/60),min=m%60;return h?`${h}h ${String(min).padStart(2,"0")}m`:`${min} min`};
  const dateLabel=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?"Unknown date":d.toLocaleDateString(undefined,{weekday:"short",day:"numeric",month:"short",year:"numeric"})};
  const timeLabel=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit"})};
  const validPoints=trip=>Array.isArray(trip?.points)?trip.points.filter(p=>Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng))).map(p=>({lat:Number(p.lat),lng:Number(p.lng),speed:Number(p.speed||0)})):[];

  async function fuelModel(){
    const active=typeof getActiveVehicle==="function"?await getActiveVehicle():null;
    const records=(await getAllRecords("fuel")).filter(r=>!active?.id||r.vehicleId==null||r.vehicleId===active.id);
    let litres=0,cost=0,distance=0;
    records.forEach(r=>{litres+=Number(r.litres||0);cost+=Number(r.cost||0);if(Number(r.distance)>0)distance+=Number(r.distance)});
    const economy=distance>0&&litres>0?litres/distance*100:null;
    const pricePerLitre=litres>0?cost/litres:null;
    const costPerKm=distance>0?cost/distance:null;
    return {economy,pricePerLitre,costPerKm};
  }
  function tripEconomics(trip,fuel){const km=Number(trip.distance||0);if(!km)return {litres:null,cost:null,costPerKm:fuel.costPerKm};const litres=fuel.economy>0?km*fuel.economy/100:null;const cost=litres!=null&&fuel.pricePerLitre!=null?litres*fuel.pricePerLitre:(fuel.costPerKm!=null?km*fuel.costPerKm:null);return {litres,cost,costPerKm:cost!=null?cost/km:fuel.costPerKm};}

  function tileXY(lat,lng,z){const n=2**z,x=(lng+180)/360*n,rad=lat*Math.PI/180,y=(1-Math.asinh(Math.tan(rad))/Math.PI)/2*n;return {x,y};}
  function chooseZoom(points,width,height){if(points.length<2)return 15;for(let z=17;z>=10;z--){const xy=points.map(p=>tileXY(p.lat,p.lng,z));const sx=Math.max(...xy.map(p=>p.x))-Math.min(...xy.map(p=>p.x));const sy=Math.max(...xy.map(p=>p.y))-Math.min(...xy.map(p=>p.y));if(sx*256<=width-48&&sy*256<=height-48)return z}return 10;}
  function mapMarkup(points,id,height=210){
    if(!points.length)return `<div class="v039-map-empty">NO GPS TRACE AVAILABLE</div>`;
    const width=760,z=chooseZoom(points,width,height),xy=points.map(p=>tileXY(p.lat,p.lng,z));
    const minX=Math.floor(Math.min(...xy.map(p=>p.x)))-2,maxX=Math.floor(Math.max(...xy.map(p=>p.x)))+2,minY=Math.floor(Math.min(...xy.map(p=>p.y)))-2,maxY=Math.floor(Math.max(...xy.map(p=>p.y)))+2;
    const originX=(minX)*256,originY=(minY)*256,tileCols=maxX-minX+1,tileRows=maxY-minY+1,tiles=[];
    for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++)tiles.push(`<img class="v039-tile" src="https://tile.openstreetmap.org/${z}/${x}/${y}.png" alt="" loading="lazy">`);
    const pts=xy.map(p=>[(p.x*256-originX),(p.y*256-originY)]),cx=pts.reduce((a,p)=>a+p[0],0)/pts.length,cy=pts.reduce((a,p)=>a+p[1],0)/pts.length,left=width/2-cx,top=height/2-cy;
    const poly=pts.map(p=>`${(p[0]+left).toFixed(1)},${(p[1]+top).toFixed(1)}`).join(" "),f=pts[0],l=pts[pts.length-1],fx=(f[0]+left).toFixed(1),fy=(f[1]+top).toFixed(1),lx=(l[0]+left).toFixed(1),ly=(l[1]+top).toFixed(1);
    return `<div class="v039-map" id="${id}" style="height:${height}px"><div class="v039-map-layer" style="width:${tileCols*256}px;height:${tileRows*256}px;left:${left}px;top:${top}px;grid-template-columns:repeat(${tileCols},256px);grid-template-rows:repeat(${tileRows},256px)">${tiles.join("")}</div><svg class="v039-route" viewBox="0 0 ${width} ${height}" preserveAspectRatio="none" aria-label="GPS route"><polyline points="${poly}" fill="none" stroke="rgba(8,12,15,.78)" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline points="${poly}" fill="none" stroke="#d8ff3e" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${fx}" cy="${fy}" r="7" fill="#fff" stroke="#111417" stroke-width="3"/><circle cx="${lx}" cy="${ly}" r="9" fill="#d8ff3e" stroke="#111417" stroke-width="3"/></svg><span class="v039-map-label start">START</span><span class="v039-map-label end">${id.startsWith("live")?"LIVE":"END"}</span><span class="v039-attribution">© OpenStreetMap contributors</span></div>`;
  }

  function styles(){if($("driveV039Styles"))return;const s=document.createElement("style");s.id="driveV039Styles";s.textContent=`.v039-map{position:relative;width:100%;overflow:hidden;border-radius:16px;background:#dfe4df}.v039-map-layer{position:absolute;display:grid;z-index:1}.v039-tile{width:256px;height:256px;display:block}.v039-route{position:absolute;inset:0;width:100%;height:100%;z-index:3;pointer-events:none}.v039-map-label{position:absolute;z-index:4;padding:5px 7px;border-radius:999px;background:rgba(255,255,255,.9);font:800 8px system-ui,sans-serif;letter-spacing:.08em;color:#111417;box-shadow:0 2px 8px rgba(0,0,0,.16)}.v039-map-label.start{left:12px;top:12px}.v039-map-label.end{right:12px;top:12px}.v039-attribution{position:absolute;right:7px;bottom:5px;z-index:5;font:7px system-ui,sans-serif;color:#333;background:rgba(255,255,255,.75);padding:2px 4px;border-radius:4px}.v039-map-empty{height:160px;display:grid;place-items:center;border-radius:16px;background:#111417;color:#8d969d;font:800 10px system-ui,sans-serif;letter-spacing:.1em}.v039-trip{border:1px solid rgba(255,255,255,.08);border-radius:18px;background:#101316;overflow:hidden;margin:0 0 12px}.v039-trip summary{list-style:none;cursor:pointer;padding:16px;display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.v039-trip summary::-webkit-details-marker{display:none}.v039-trip-title{font-size:14px;font-weight:800}.v039-trip-meta{display:block;margin-top:5px;color:#8d969d;font-size:10px}.v039-trip-cost{text-align:right}.v039-trip-cost strong{display:block;font-size:14px}.v039-trip-cost span{display:block;color:#8d969d;font-size:8px;letter-spacing:.08em;margin-top:3px}.v039-details{padding:0 12px 12px}.v039-metrics{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:10px 0}.v039-metric{padding:11px;border-radius:12px;background:#171b1f;border:1px solid rgba(255,255,255,.06)}.v039-metric span{display:block;color:#818a91;font-size:8px;font-weight:800;letter-spacing:.1em}.v039-metric strong{display:block;margin-top:5px;font-size:13px}.v039-note{margin:10px 0 0;padding:10px 12px;border-radius:10px;background:rgba(216,255,62,.06);color:#aeb5ba;font-size:9px;line-height:1.5}.v039-section-label{margin:12px 2px 7px;color:#7f888f;font-size:8px;font-weight:800;letter-spacing:.12em}.v039-live-map{margin:12px 0}.v039-live-map .v039-map{height:190px!important}@media(min-width:481px){.v039-metrics{grid-template-columns:repeat(4,1fr)}}@media(prefers-reduced-motion:reduce){.v039-trip summary{scroll-behavior:auto}}`;document.head.appendChild(s)}

  let livePoints=[],liveBound=false,liveCard=null;
  function mountLive(){styles();const card=$("tripLiveCard");if(!card)return;if(!$("driveV039LiveMap")){const old=$("driveLiveMapWrap");if(old)old.remove();const wrap=document.createElement("div");wrap.id="driveV039LiveMap";wrap.className="v039-live-map";wrap.innerHTML=mapMarkup([],"liveTripMap",190);const stop=$("stopDriveButton");card.insertBefore(wrap,stop||null)}liveCard=$("driveV039LiveMap")}
  function updateLive(point){if(!point||!Number.isFinite(Number(point.lat))||!Number.isFinite(Number(point.lng)))return;livePoints.push({lat:Number(point.lat),lng:Number(point.lng)});mountLive();if(liveCard)liveCard.innerHTML=mapMarkup(livePoints,"liveTripMap",190);}
  function resetLive(){livePoints=[];if(liveCard)liveCard.innerHTML=mapMarkup([],"liveTripMap",190)}
  function bindLive(){if(liveBound)return;document.addEventListener("gpsupdate",e=>{if(window.DRIVE_APP?.isTripActive())updateLive(e.detail.point)});liveBound=true}

  async function renderTripsV039(){
    styles();const history=$("tripHistory");if(!history)return;const active=typeof getActiveVehicle==="function"?await getActiveVehicle():null;const trips=(await getAllRecords("trips")).filter(r=>!active?.id||r.vehicleId==null||r.vehicleId===active.id).sort((a,b)=>new Date(b.startTime||b.createdAt)-new Date(a.startTime||a.createdAt));
    const empty=document.querySelector("#tripsPage .empty-state");if(!trips.length){history.innerHTML="";if(empty)empty.style.display="block";return}if(empty)empty.style.display="none";
    const fuel=await fuelModel();
    history.innerHTML=trips.map((trip,index)=>{const start=new Date(trip.startTime||trip.createdAt),end=new Date(trip.endTime||trip.startTime||trip.createdAt),ms=Number(trip.duration)>0?Number(trip.duration):Math.max(0,end-start),km=Number(trip.distance||0),avg=ms>0?km/(ms/3600000):0,pts=validPoints(trip),max=pts.length?Math.max(...pts.map(p=>p.speed*3.6).filter(Number.isFinite)):0,eco=tripEconomics(trip,fuel);return `<details class="v039-trip" ${index===0?"open":""}><summary><div><div class="v039-trip-title">${esc(dateLabel(start))} · ${km.toFixed(2)} km</div><span class="v039-trip-meta">${esc(timeLabel(start))} → ${esc(timeLabel(end))} · ${duration(ms)} · ${pts.length.toLocaleString()} GPS points</span></div><div class="v039-trip-cost"><strong>${eco.cost!=null?money(eco.cost):"—"}</strong><span>EST. FUEL COST</span></div></summary><div class="v039-details"><div class="v039-section-label">ROUTE</div>${mapMarkup(pts,`tripMapV039_${trip.id||index}`,210)}<div class="v039-section-label">TRIP DATA</div><div class="v039-metrics"><div class="v039-metric"><span>DISTANCE</span><strong>${km.toFixed(2)} km</strong></div><div class="v039-metric"><span>DURATION</span><strong>${duration(ms)}</strong></div><div class="v039-metric"><span>AVG SPEED</span><strong>${avg>0?avg.toFixed(0):"—"} km/h</strong></div><div class="v039-metric"><span>MAX SPEED</span><strong>${max>0?max.toFixed(0):"—"} km/h</strong></div><div class="v039-metric"><span>EST. FUEL</span><strong>${eco.litres!=null?eco.litres.toFixed(2):"—"} L</strong></div><div class="v039-metric"><span>FUEL COST</span><strong>${eco.cost!=null?money(eco.cost):"—"}</strong></div><div class="v039-metric"><span>COST / KM</span><strong>${eco.costPerKm!=null?money(eco.costPerKm):"—"}</strong></div><div class="v039-metric"><span>GPS TRACE</span><strong>${pts.length?pts.length.toLocaleString():"None"}</strong></div></div>${eco.cost!=null?`<div class="v039-note">Estimated from your recorded fuel history${fuel.economy?` using ${fuel.economy.toFixed(2)} L/100 km`:""}${fuel.pricePerLitre?` and an average fuel price of ${money(fuel.pricePerLitre)}/L`:""}. This is an estimate, not a direct fuel measurement.</div>`:`<div class="v039-note">Add fuel records with litres, cost and odometer distance to calculate this trip's estimated fuel cost.</div>`}</div></details>`}).join("");
  }
  function init(){styles();window.renderTrips=renderTripsV039;bindLive();renderTripsV039();}
  window.DRIVE_TRIPS_V039={refresh:renderTripsV039,mountLive,updateLive,resetLive};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
