/* DRIVE v0.38 — Live Drive Intelligence */
(function(){
  "use strict";
  const TILE_URL="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
  const ATTRIBUTION='&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors';
  let map=null,marker=null,routeLine=null,accuracyCircle=null,points=[],speeds=[];
  const $=id=>document.getElementById(id);
  function styles(){if($("driveLiveMapStyles"))return;const s=document.createElement("style");s.id="driveLiveMapStyles";s.textContent=`.live-map-wrap{margin:14px 0 12px;border:1px solid rgba(255,255,255,.08);border-radius:14px;overflow:hidden;background:#0d1012}.live-map{height:240px;width:100%;background:#111417}.live-map-status{position:absolute;z-index:500;top:10px;left:10px;padding:6px 9px;border:1px solid rgba(255,255,255,.1);border-radius:999px;background:rgba(13,16,18,.86);backdrop-filter:blur(8px);font-size:9px;font-weight:800;letter-spacing:.09em;color:#c9d4ce}.live-map-pane{position:relative}.live-telemetry{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:10px}.live-telemetry>div{padding:10px 11px;border:1px solid rgba(255,255,255,.07);border-radius:10px;background:#111417}.live-telemetry span{display:block;color:#858c93;font-size:8px;letter-spacing:.1em;font-weight:800}.live-telemetry strong{display:block;margin-top:5px;font-size:13px}.leaflet-control-attribution{font-size:8px!important}@media(min-width:481px){.live-telemetry{grid-template-columns:repeat(4,1fr)}}@media(max-width:480px){.live-map{height:210px}}`;
  document.head.appendChild(s)}
  function mount(){styles();const card=$("tripLiveCard");if(!card)return;let w=$("driveLiveMapWrap");if(!w){w=document.createElement("div");w.id="driveLiveMapWrap";w.className="live-map-wrap";w.innerHTML='<div class="live-map-pane"><div class="live-map-status" id="liveMapStatus">WAITING FOR GPS</div><div id="driveLiveMap" class="live-map" role="img" aria-label="Live drive map showing your current position and route"></div></div><div class="live-telemetry"><div><span>SPEED</span><strong id="liveSpeed">— KM/H</strong></div><div><span>AVG SPEED</span><strong id="liveAverageSpeed">— KM/H</strong></div><div><span>DISTANCE</span><strong id="liveMapDistance">0.00 KM</strong></div><div><span>GPS QUALITY</span><strong id="liveGpsQuality">—</strong></div></div>';const stop=$("stopDriveButton");card.insertBefore(w,stop||null)}if(!window.L||map)return;map=L.map("driveLiveMap",{zoomControl:false,attributionControl:true,preferCanvas:true}).setView([-23.685,24.411],15);L.tileLayer(TILE_URL,{maxZoom:19,attribution:ATTRIBUTION}).addTo(map);routeLine=L.polyline([],{weight:4,smoothFactor:1}).addTo(map)}
  function quality(a){if(!Number.isFinite(a))return "WAITING";if(a<=10)return "EXCELLENT";if(a<=25)return "GOOD";if(a<=50)return "FAIR";return "WEAK"}
  function update(point,distance){mount();if(!map)return;const ll=[point.lat,point.lng];points.push(ll);const speed=Number.isFinite(point.speed)&&point.speed>=0?point.speed*3.6:0;speeds.push(speed);if(!marker)marker=L.circleMarker(ll,{radius:8,weight:3,fillOpacity:.95}).addTo(map);else marker.setLatLng(ll);if(!accuracyCircle)accuracyCircle=L.circle(ll,{radius:Math.min(point.accuracy||0,100),weight:1,fillOpacity:.08}).addTo(map);else accuracyCircle.setLatLng(ll).setRadius(Math.min(point.accuracy||0,100));routeLine?.setLatLngs(points);map.setView(ll,Math.max(map.getZoom(),15),{animate:false});$("liveSpeed")&&($("liveSpeed").textContent=`${speed.toFixed(0)} KM/H`);$("liveAverageSpeed")&&($("liveAverageSpeed").textContent=`${(speeds.reduce((a,b)=>a+b,0)/speeds.length).toFixed(0)} KM/H`);$("liveMapDistance")&&($("liveMapDistance").textContent=`${Number(distance||0).toFixed(2)} KM`);$("liveGpsQuality")&&($("liveGpsQuality").textContent=quality(point.accuracy));$("liveMapStatus")&&($("liveMapStatus").textContent="GPS LIVE")}
  function reset(){points=[];speeds=[];routeLine?.setLatLngs([]);marker?.remove();accuracyCircle?.remove();marker=null;accuracyCircle=null;if($("liveMapStatus"))$("liveMapStatus").textContent="WAITING FOR GPS";if($("liveSpeed"))$("liveSpeed").textContent="— KM/H";if($("liveAverageSpeed"))$("liveAverageSpeed").textContent="— KM/H";if($("liveGpsQuality"))$("liveGpsQuality").textContent="—"}
  function init(){styles();mount();document.addEventListener("gpsupdate",e=>{if(window.DRIVE_APP?.isTripActive())update(e.detail.point,e.detail.distance)});window.addEventListener("drive:datachanged",()=>{if(!window.DRIVE_APP?.isTripActive())reset()})}
  window.DRIVE_LIVE_V038={init,reset};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();