/* DRIVE v0.36 — Maintenance Intelligence 2.0 */
(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`P${Number(v||0).toFixed(2)}`;
const vehicleMatch=(r,v)=>!v?.id||r.vehicleId==null||String(r.vehicleId)===String(v.id);
async function analyse(){
 const vehicle=await getActiveVehicle();
 const rows=(await getAllRecords('maintenance')).filter(r=>vehicleMatch(r,vehicle)).sort((a,b)=>new Date(b.date||b.createdAt)-new Date(a.date||a.createdAt));
 const odo=Number(vehicle?.odometer||0), scheduled=rows.filter(r=>Number(r.nextServiceOdometer)>0||r.nextServiceDate);
 const next=scheduled.slice().sort((a,b)=>{const ak=Number(a.nextServiceOdometer)>0?Number(a.nextServiceOdometer):Infinity,bk=Number(b.nextServiceOdometer)>0?Number(b.nextServiceOdometer):Infinity;return ak-bk})[0]||null;
 let kmRemaining=null,daysRemaining=null,status='unknown';
 if(next){if(Number(next.nextServiceOdometer)>0)kmRemaining=Number(next.nextServiceOdometer)-odo;if(next.nextServiceDate){const d=new Date(`${next.nextServiceDate}T00:00:00`);if(!Number.isNaN(d.getTime()))daysRemaining=Math.ceil((d-Date.now())/86400000)}const overdue=(kmRemaining!=null&&kmRemaining<=0)||(daysRemaining!=null&&daysRemaining<=0);const dueSoon=!overdue&&((kmRemaining!=null&&kmRemaining<=1000)||(daysRemaining!=null&&daysRemaining<=30));status=overdue?'overdue':dueSoon?'due-soon':'ok'}
 return{vehicle,records:rows,last:rows[0]||null,next,kmRemaining,daysRemaining,status,totalSpend:rows.reduce((s,r)=>s+Math.max(0,Number(r.cost)||0),0)};
}
function styles(){if(document.getElementById('drive-v036-maint-style'))return;const s=document.createElement('style');s.id='drive-v036-maint-style';s.textContent=`.maintenance-v036{margin-top:18px}.m36-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.m36-head h3{margin:5px 0 0;font-size:18px;letter-spacing:-.02em}.m36-status{font-size:10px;font-weight:850;letter-spacing:.08em;text-transform:uppercase}.m36-status.overdue{color:var(--danger)}.m36-status.due-soon{color:var(--warning)}.m36-status.ok{color:var(--accent)}.m36-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:14px}.m36-card{padding:13px;border:1px solid var(--line);border-radius:13px;background:var(--surface-2)}.m36-card span{display:block;color:var(--muted);font-size:9px;font-weight:800;letter-spacing:.08em}.m36-card strong{display:block;margin-top:6px;font-size:17px}.m36-card small{display:block;margin-top:4px;color:var(--muted);font-size:10px}.m36-note{margin:12px 0 0;color:var(--muted);font-size:11px;line-height:1.5}.m36-actions{display:flex;justify-content:flex-end;margin-top:12px}.m36-actions button{min-height:40px;padding:0 14px;border:1px solid var(--line);border-radius:10px;background:var(--surface-2);color:var(--text);font-weight:800;font-size:10px}@media(max-width:600px){.m36-grid{grid-template-columns:1fr 1fr}.m36-card:last-child{grid-column:1/-1}.m36-head{display:block}.m36-status{display:block;margin-top:8px}}`;document.head.appendChild(s)}
function render(r){styles();const anchor=document.getElementById('usageIntelligence')||document.getElementById('costIntelligence')||document.getElementById('driveBriefing');if(!anchor)return;document.getElementById('maintenanceIntelligenceV36')?.remove();const section=document.createElement('section');section.id='maintenanceIntelligenceV36';section.className='panel maintenance-v036';const statusLabel=r.status==='overdue'?'OVERDUE':r.status==='due-soon'?'DUE SOON':r.status==='ok'?'ON TRACK':'BUILDING';const nextTarget=r.next?(r.kmRemaining!=null?`${Math.max(0,r.kmRemaining).toLocaleString()} km`:r.daysRemaining!=null?`${Math.max(0,r.daysRemaining)} days`:'Set interval'):'—';const note=r.status==='overdue'?'A scheduled service target has been reached or passed. Record the service when completed so DRIVE can reset the next interval.':r.status==='due-soon'?'Your next recorded service target is approaching. Plan the service and keep the record current.':r.status==='ok'?'Your recorded service schedule is currently on track.':'Add service records with km/month intervals to let DRIVE monitor maintenance timing.';section.innerHTML=`<div class="m36-head"><div><span class="eyebrow">MAINTENANCE INTELLIGENCE 2.0</span><h3>Service timing & history</h3></div><span class="m36-status ${r.status}">${statusLabel}</span></div><div class="m36-grid"><div class="m36-card"><span>NEXT SERVICE</span><strong>${nextTarget}</strong><small>${r.next?esc(r.next.title||'Scheduled service'):'No scheduled service'}</small></div><div class="m36-card"><span>LAST SERVICE</span><strong>${r.last?esc(r.last.date):'—'}</strong><small>${r.last?`${Number(r.last.odometer||0).toLocaleString()} km · ${money(r.last.cost)}`:'Record your first service'}</small></div><div class="m36-card"><span>RECORDS</span><strong>${r.records.length}</strong><small>${r.totalSpend?`${money(r.totalSpend)} recorded maintenance spend`:'No maintenance spend recorded'}</small></div></div><p class="m36-note">${note}</p><div class="m36-actions"><button type="button" id="maintenanceV36Button">${r.records.length?'RECORD / VIEW SERVICE':'ADD SERVICE'}</button></div>`;anchor.insertAdjacentElement('afterend',section);section.querySelector('#maintenanceV36Button')?.addEventListener('click',()=>window.DRIVE_MAINTENANCE?.openMaintenance?.())}
async function refresh(){try{const r=await analyse();window.DRIVE_MAINTENANCE_V36_LAST=r;render(r);return r}catch(e){console.error('DRIVE maintenance intelligence failed',e)}}
window.DRIVE_MAINTENANCE_V36={analyse,refresh};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',refresh,{once:true});else refresh();
window.addEventListener('drive:datachanged',refresh);
})();
