/* DRIVE — Maintenance */
(()=>{
"use strict";
const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const money=v=>`P${Number(v||0).toFixed(2)}`;
const today=()=>new Date().toISOString().slice(0,10);
const notify=m=>typeof announce==="function"?announce(m):console.info(m);
const match=(r,v)=>!v?.id||r.vehicleId==null||String(r.vehicleId)===String(v.id);
async function componentsFor(v){try{if(window.DRIVE_COMPONENTS?.list)return(await window.DRIVE_COMPONENTS.list()).filter(r=>match(r,v));if(typeof indexedDB==="undefined")return[];return await new Promise((resolve,reject)=>{const req=indexedDB.open("drive-db",4);req.onsuccess=()=>{const db=req.result;try{const q=db.transaction("components","readonly").objectStore("components").getAll();q.onsuccess=()=>{db.close();resolve((q.result||[]).filter(r=>match(r,v)))};q.onerror=()=>{db.close();reject(q.error)}}catch(e){db.close();reject(e)}};req.onerror=()=>reject(req.error)})}catch(e){console.warn("Component lookup unavailable",e);return[]}}
function ensureModal(){let m=document.getElementById("maintenanceModal");if(!m){m=document.createElement("div");m.id="maintenanceModal";m.className="modal hidden";m.innerHTML=`<div class="modal-sheet"><div class="modal-header"><div><span class="eyebrow">SERVICE RECORD</span><h2>Maintenance</h2></div><button type="button" class="modal-close" data-maintenance-close aria-label="Close maintenance">×</button></div><form id="maintenanceForm"><label>Service / repair<input id="maintenanceTitle" required maxlength="100"></label><label>Component<select id="maintenanceComponent"><option value="">General / not linked</option></select></label><label>Notes<textarea id="maintenanceDescription" rows="3" maxlength="500"></textarea></label><label>Odometer<div class="input-unit"><input id="maintenanceOdometer" type="number" min="0" step="1" required><span>KM</span></div></label><label>Cost<div class="input-unit"><span>P</span><input id="maintenanceCost" type="number" min="0" step="0.01" value="0"></div></label><label>Date<input id="maintenanceDate" type="date" required></label><div class="form-grid"><div><label>Next service interval (km)<input id="maintenanceIntervalKm" type="number" min="0" step="1"></label><small>Optional</small></div><div><label>Next service interval (months)<input id="maintenanceIntervalMonths" type="number" min="0" step="1"></label><small>Optional</small></div></div><p id="maintenanceSaveError" class="form-error" role="alert" hidden></p><button class="submit-button" type="submit">SAVE SERVICE</button></form><div id="maintenanceHistory" class="tool-history"></div></div>`;document.body.appendChild(m)}if(!m.querySelector("#maintenanceHistory")){const sheet=m.querySelector(".modal-sheet")||m,h=document.createElement("div");h.id="maintenanceHistory";h.className="tool-history";sheet.appendChild(h)}return m}
async function vehicle(){let v=await getActiveVehicle();if(!v&&typeof ensureDefaultVehicle==="function")v=await ensureDefaultVehicle();return v}
async function componentMap(v){const rows=await componentsFor(v);return new Map(rows.map(r=>[String(r.id),r]))}
async function populateComponents(m,v,selected=""){const select=m.querySelector("#maintenanceComponent");if(!select)return;const rows=await componentsFor(v);select.innerHTML=`<option value="">General / not linked</option>`+rows.sort((a,b)=>String(a.name||"").localeCompare(String(b.name||""))).map(r=>`<option value="${esc(r.id)}">${esc(r.name)} · ${esc(r.category||"Other")}</option>`).join("");select.value=selected&&rows.some(r=>String(r.id)===String(selected))?String(selected):""}
async function renderHistory(m){const list=m.querySelector("#maintenanceHistory"),v=await vehicle(),cMap=await componentMap(v),rows=(await getAllRecords("maintenance")).filter(r=>match(r,v)).sort((a,b)=>String(b.date||b.createdAt).localeCompare(String(a.date||a.createdAt)));list.innerHTML=`<div class="tool-history-title">SERVICE HISTORY</div>`+(rows.length?rows.slice(0,20).map(r=>{const c=r.componentId?cMap.get(String(r.componentId)):null;return `<div class="tool-history-row maintenance-history-row"><span><strong>${esc(r.title||"Maintenance")}</strong><small>${esc(r.date||"")} · ${Number(r.odometer||0).toLocaleString()} km${c?` · ${esc(c.name)}`:""}</small></span><span class="history-row-end"><b>${money(r.cost)}</b><button type="button" class="history-delete" data-maintenance-delete="${r.id}">×</button></span></div>`}).join(""):"<p class=\"tool-empty\">No service records yet.</p>");list.querySelectorAll("[data-maintenance-delete]").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this service record?"))return;await deleteRecord("maintenance",Number(b.dataset.maintenanceDelete));await renderHistory(m);window.dispatchEvent(new CustomEvent("drive:datachanged",{detail:{store:"maintenance"}}))})}
async function save(e){e.preventDefault();const m=ensureModal(),form=e.currentTarget,v=await vehicle(),q=id=>m.querySelector(`#${id}`),err=q("maintenanceSaveError");if(!v){err.textContent="Vehicle is not ready. Reload DRIVE and try again.";err.hidden=false;return}const title=q("maintenanceTitle").value.trim(),description=q("maintenanceDescription").value.trim(),odometer=Number(q("maintenanceOdometer").value),cost=Number(q("maintenanceCost").value||0),date=q("maintenanceDate").value||today(),kmInt=Number(q("maintenanceIntervalKm").value||0),moInt=Number(q("maintenanceIntervalMonths").value||0),componentId=q("maintenanceComponent").value||null;if(!title||!Number.isFinite(odometer)||odometer<0||!Number.isFinite(cost)||cost<0){err.textContent="Check the service details and try again.";err.hidden=false;return}let nextDate=null;if(moInt>0){const d=new Date(`${date}T00:00:00`);d.setMonth(d.getMonth()+moInt);nextDate=d.toISOString().slice(0,10)}const record={vehicleId:v.id,title,description,odometer,cost,date,componentId,intervalKm:kmInt||null,intervalMonths:moInt||null,nextServiceOdometer:kmInt>0?odometer+kmInt:null,nextServiceDate:nextDate,createdAt:new Date().toISOString(),synced:false};const btn=form.querySelector("button[type=submit]");try{btn.disabled=true;const id=await addRecord("maintenance",record);if(odometer>Number(v.odometer||0)){v.odometer=odometer;await putRecord("vehicles",v)}await renderHistory(m);form.reset();q("maintenanceDate").value=today();await populateComponents(m,v);m.classList.add("hidden");notify(`Service saved: ${title}.`);window.dispatchEvent(new CustomEvent("drive:datachanged",{detail:{store:"maintenance",id,componentId}}))}catch(error){console.error(error);err.textContent="Service could not be saved. Please try again.";err.hidden=false}finally{btn.disabled=false}}
function bind(){const m=ensureModal(),f=m.querySelector("#maintenanceForm");if(!f.dataset.bound){f.dataset.bound="1";f.addEventListener("submit",save)}const c=m.querySelector("[data-maintenance-close]");if(c&&!c.dataset.bound){c.dataset.bound="1";c.onclick=()=>m.classList.add("hidden")}}
async function openMaintenance(){const m=ensureModal();bind();const v=await vehicle();m.querySelector("#maintenanceOdometer").value=v?.odometer||"";m.querySelector("#maintenanceDate").value=today();await populateComponents(m,v);await renderHistory(m);m.classList.remove("hidden");m.querySelector("#maintenanceTitle").focus()}
async function refresh(){try{const m=ensureModal();await renderHistory(m);document.getElementById("serviceIntel")?.remove()}catch(e){console.error("Maintenance refresh failed",e)}}
window.DRIVE_MAINTENANCE={refresh,openMaintenance,mountForm:()=>{bind();return ensureModal()},renderHistory};
function boot(){bind();refresh()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
