/* DRIVE v0.53 — Predictive Vehicle Intelligence */
(()=>{
"use strict";
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
const finite=v=>Number.isFinite(Number(v))?Number(v):null;
const avg=a=>{const x=a.map(finite).filter(v=>v!=null);return x.length?x.reduce((s,v)=>s+v,0)/x.length:null};
const median=a=>{const x=a.map(finite).filter(v=>v!=null).sort((a,b)=>a-b);if(!x.length)return null;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const pct=(a,b)=>b?((a-b)/b)*100:null;
const days=(a,b)=>Math.ceil((new Date(a)-new Date(b))/86400000);
function fuel(data){const rows=data.fuel.filter(r=>finite(r.litres)>0&&finite(r.distance)>0).sort((a,b)=>new Date(a.date||a.createdAt)-new Date(b.date||b.createdAt));if(rows.length<4)return null;const economy=rows.map(r=>finite(r.economy)>0?finite(r.economy):finite(r.litres)/finite(r.distance)*100),price=rows.map(r=>finite(r.cost)/finite(r.litres)).filter(v=>v>0);const recent=avg(economy.slice(-3)),base=median(economy.slice(0,-3)),fuelPrice=avg(price.slice(-6));if(!recent||!base)return null;const change=pct(recent,base);let severity="info",message="Fuel use is tracking close to your recorded pattern.";if(change>=15){severity="watch";message=`Recent consumption is ${Math.abs(change).toFixed(0)}% above your earlier baseline.`}else if(change<=-15){severity="positive";message=`Recent consumption is ${Math.abs(change).toFixed(0)}% better than your earlier baseline.`}return{id:"fuel-forecast",type:"fuel",severity,title:"FUEL FORECAST",message,action:"Keep logging complete fill-ups; DRIVE will refine the forecast as the sample grows.",confidence:clamp(.55+rows.length*.04,.55,.95),evidence:{recentEconomy:`${recent.toFixed(2)} L/100 km`,baseline:`${base.toFixed(2)} L/100 km`,change:`${change.toFixed(1)}%`,fuelPrice:fuelPrice?`P${fuelPrice.toFixed(2)}/L`:"—",samples:rows.length}}}
function usage(data){const trips=data.trips.filter(t=>finite(t.distance)>0).sort((a,b)=>new Date(a.endTime||a.startTime||a.createdAt)-new Date(b.endTime||b.startTime||b.createdAt));if(trips.length<6)return null;const d=trips.map(t=>finite(t.distance)),recent=avg(d.slice(-4)),previous=avg(d.slice(-8,-4)),rate=avg(trips.slice(-6).map(t=>finite(t.distance)/Math.max(1,(new Date(t.endTime||t.startTime||t.createdAt)-new Date(t.startTime||t.createdAt))/86400000)));if(!recent||!previous)return null;const change=pct(recent,previous);return{id:"usage-forecast",type:"driving",severity:change>25?"watch":"info",title:"USAGE FORECAST",message:`Your recent average drive is ${recent.toFixed(1)} km; the prior period averaged ${previous.toFixed(1)} km.`,action:change>25?"If this pattern continues, expect higher fuel and running-cost demand.":"No action required; keep recording drives.",confidence:clamp(.55+trips.length*.025,.55,.9),evidence:{recentAverage:`${recent.toFixed(1)} km`,previousAverage:`${previous.toFixed(1)} km`,change:`${change.toFixed(1)}%`,recentDailyDistance:rate?`${rate.toFixed(1)} km/day`:"—",samples:trips.length}}}
function service(data){const m=data.maintenance.filter(r=>finite(r.nextServiceOdometer)>0||r.nextServiceDate).sort((a,b)=>new Date(b.date||b.createdAt)-new Date(a.date||a.createdAt))[0];const odo=finite(data.vehicle?.odometer);if(!m)return null;const target=finite(m.nextServiceOdometer),km=target&&odo?target-odo:null,date=m.nextServiceDate?days(m.nextServiceDate,new Date()):null;let severity="info";if((km!=null&&km<=0)||(date!=null&&date<0))severity="attention";else if((km!=null&&km<=750)||(date!=null&&date<=45))severity="watch";const message=severity==="attention"?"A recorded service threshold has likely been reached.":severity==="watch"?"A recorded service threshold is approaching.":"The next recorded service interval is still ahead.";return{id:"service-forecast",type:"maintenance",severity,title:"SERVICE FORECAST",message,action:severity==="attention"?"Review and schedule the recorded service before the next planned use.":severity==="watch"?"Plan the service and update the record when completed.":"Keep the interval current after each service.",confidence:.95,evidence:{odometer:odo?`${odo.toLocaleString()} km`:"—",nextServiceOdometer:target?`${target.toLocaleString()} km`:"—",kmRemaining:km!=null?`${Math.max(0,km).toLocaleString()} km`:"—",daysRemaining:date!=null?date:"—"}}}
function cost(data){const rows=[...data.fuel.map(r=>({date:r.date||r.createdAt,cost:finite(r.cost)||0})),...data.expenses.map(r=>({date:r.date||r.createdAt,cost:finite(r.amount)||0})),...data.maintenance.map(r=>({date:r.date||r.createdAt,cost:finite(r.cost)||0}))].filter(r=>!Number.isNaN(new Date(r.date).getTime()));const months=new Map();rows.forEach(r=>{const d=new Date(r.date),k=`${d.getFullYear()}-${d.getMonth()}`;months.set(k,(months.get(k)||0)+r.cost)});const vals=[...months.values()].slice(-4);if(vals.length<3)return null;const recent=avg(vals.slice(-2)),older=avg(vals.slice(0,-2));if(recent==null||older==null)return null;const change=pct(recent,older);return{id:"cost-forecast",type:"cost",severity:change>=20?"watch":"info",title:"RUNNING COST FORECAST",message:`Recent monthly running cost is averaging about P${recent.toFixed(0)}.`,action:change>=20?"Review the recent fuel, maintenance and expense entries driving the increase.":"Keep recording costs to improve the forecast.",confidence:clamp(.55+vals.length*.06,.55,.85),evidence:{recentMonthlyAverage:`P${recent.toFixed(0)}`,earlierMonthlyAverage:`P${older.toFixed(0)}`,change:`${change.toFixed(1)}%`,months:vals.length}}}
function confidence(items){return items.length?Math.round(avg(items.map(x=>x.confidence))*100):0}
async function analyse(){const data=await window.DRIVE_DATA.snapshot(),insights=[fuel(data),usage(data),service(data),cost(data)].filter(Boolean);const predictive=insights.filter(x=>x.severity!=="info"||x.type==="maintenance");return{data,insights,predictive,confidence:confidence(insights),generatedAt:new Date().toISOString()}}
function render(r){const host=document.getElementById("driveBriefing");if(!host)return;const items=r.insights.slice().sort((a,b)=>({attention:0,watch:1,positive:2,info:3}[a.severity]??9)-({attention:0,watch:1,positive:2,info:3}[b.severity]??9)).slice(0,3);host.innerHTML=`<div class="panel-header"><div><span class="eyebrow">DRIVE INTELLIGENCE</span><h2>DRIVE BRIEFING</h2></div><span class="briefing-confidence">${r.confidence}% CONFIDENCE</span></div><div class="briefing-list">${items.length?items.map(i=>`<article class="briefing-item severity-${esc(i.severity)}"><div class="briefing-title"><strong>${esc(i.title)}</strong><span>${esc(i.severity.toUpperCase())}</span></div><p>${esc(i.message)}</p><small>${esc(i.action)}</small></article>`).join(""):"<div class=\"briefing-empty\"><strong>Building your forecast</strong><p>Keep recording fuel, drives, service and costs.</p></div>"}</div>`}
async function refresh(){try{const r=await analyse();render(r);return r}catch(e){console.error("DRIVE predictive intelligence failed",e);return null}}
window.DRIVE_PREDICTIVE={analyse,refresh};window.addEventListener("drive:datachanged",()=>refresh());if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(refresh,250),{once:true});else setTimeout(refresh,250);
})();
