/* DRIVE v0.29 — Vehicle Memory + More tools */
(()=>{
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const active=()=>typeof getActiveVehicle==='function'?getActiveVehicle():null;
const records=async store=>{const v=await active();return (await getAllRecords(store)).filter(r=>!v?.id||!r.vehicleId||r.vehicleId===v.id)};
function modal(id,title,body){let m=document.getElementById(id);if(m)return m;m=document.createElement('div');m.id=id;m.className='modal hidden';m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.innerHTML=`<div class="modal-sheet"><div class="modal-handle" aria-hidden="true"></div><div class="modal-header"><div><span class="eyebrow">DRIVE</span><h2>${title}</h2></div><button type="button" class="modal-close" data-close="${id}" aria-label="Close">×</button></div>${body}</div>`;document.body.appendChild(m);m.querySelector('[data-close]')?.addEventListener('click',()=>m.classList.add('hidden'));return m}
function open(id){document.getElementById(id)?.classList.remove('hidden')}
async function expense(){const m=modal('expenseModal','Expense',`<form id="expenseForm"><label for="expenseTitle">Description<input id="expenseTitle" required maxlength="100" placeholder="Car wash, parts, parking…"></label><label for="expenseCategory">Category<select id="expenseCategory"><option>General</option><option>Fuel</option><option>Maintenance</option><option>Tyres</option><option>Insurance</option><option>Licensing</option><option>Other</option></select></label><label for="expenseCost">Amount<div class="input-unit"><span>P</span><input id="expenseCost" type="number" min="0" step="0.01" required placeholder="250.00"></div></label><label for="expenseDate">Date<input id="expenseDate" type="date" required></label><button class="submit-button" type="submit">SAVE EXPENSE</button></form>`);m.querySelector('#expenseDate').value=new Date().toISOString().split('T')[0];m.querySelector('#expenseForm').onsubmit=async e=>{e.preventDefault();const v=await active();await addRecord('expenses',{vehicleId:v?.id,title:m.querySelector('#expenseTitle').value.trim(),category:m.querySelector('#expenseCategory').value,cost:Number(m.querySelector('#expenseCost').value),date:m.querySelector('#expenseDate').value,createdAt:new Date().toISOString(),synced:false});m.classList.add('hidden');e.target.reset();m.querySelector('#expenseDate').value=new Date().toISOString().split('T')[0];window.dispatchEvent(new CustomEvent('drive:datachanged',{detail:{store:'expenses'}}));};open('expenseModal')}
function maintenance(){window.DRIVE_MAINTENANCE?.openMaintenance?.()}
function documents(){const m=modal('documentsModal','Documents',`<div class="document-tool"><p>Keep important vehicle records in DRIVE. Files are stored locally on this device.</p><label class="file-drop" for="driveDocumentInput"><strong>ADD DOCUMENT</strong><span>PDF, image or other file</span><input id="driveDocumentInput" type="file" accept="image/*,.pdf,.txt,.doc,.docx" hidden></label><div id="documentList" class="document-list"></div></div>`);m.querySelector('#driveDocumentInput').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const v=await active();await addRecord('documents',{vehicleId:v?.id,name:file.name,type:file.type,size:file.size,file,createdAt:new Date().toISOString(),synced:false});await renderDocuments(m);e.target.value='';};renderDocuments(m);open('documentsModal')}
async function renderDocuments(m){if(!m)return;const rows=await records('documents');const list=m.querySelector('#documentList');if(!list)return;list.innerHTML=rows.slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,30).map(r=>`<article class="document-row"><button type="button" class="document-open" data-doc-id="${r.id}"><span class="document-icon">DOC</span><span><strong>${esc(r.name)}</strong><small>${new Date(r.createdAt).toLocaleDateString()} · ${Math.max(1,Math.round((r.size||0)/1024))} KB</small></span></button></article>`).join('')||'<div class="briefing-empty"><strong>No documents yet</strong><p>Add service invoices, registration records or other vehicle documents.</p></div>';list.querySelectorAll('[data-doc-id]').forEach(b=>b.onclick=async()=>{const r=rows.find(x=>String(x.id)===String(b.dataset.docId));if(!r?.file)return;const url=URL.createObjectURL(r.file);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)})}
function more(){const page=document.getElementById('morePage');if(!page)return;page.classList.add('more-modern');const list=page.querySelector('.settings-list');if(!list)return;const items=[['maintenance','Maintenance','Service history, intervals and next service'],['expense','Expenses','Track running costs beyond fuel'],['documents','Documents','Keep vehicle records organised'],['camera','Camera / OCR','Scan fuel, odometer and service records'],['analytics','Analytics','See cost, fuel and distance trends'],['backup','Data & Backup','Protect and move your local data'],['settings','Settings','Vehicle profile and app preferences']];list.innerHTML=items.map(([id,t,s])=>`<button type="button" data-more-action="${id}"><span class="more-copy"><strong>${t}</strong><small>${s}</small></span><span class="more-arrow" aria-hidden="true">›</span></button>`).join('');list.addEventListener('click',e=>{const b=e.target.closest('[data-more-action]');if(!b)return;const a=b.dataset.moreAction;if(a==='expense')expense();else if(a==='maintenance')maintenance();else if(a==='documents')documents();else if(a==='camera')window.DRIVE_CAMERA?.open();else if(a==='analytics'){showPage?.('analyticsView');window.DRIVE_ANALYTICS?.refresh?.()}else if(a==='backup'){document.getElementById('dataToolsModal')?.classList.remove('hidden')}else if(a==='settings')window.DRIVE_VEHICLE_SETTINGS?.open?.()})}
async function memory(){const fuel=await records('fuel'),trips=await records('trips'),expenses=await records('expenses'),maintenanceRows=await records('maintenance');const economies=fuel.map(r=>Number(r.economy)).filter(Number.isFinite).filter(v=>v>0&&v<40),costs=expenses.concat(fuel.map(r=>({cost:r.cost})),maintenanceRows.map(r=>({cost:r.cost}))).map(r=>Number(r.cost)).filter(Number.isFinite).filter(v=>v>=0),dist=trips.map(r=>Number(r.distance)).filter(v=>Number.isFinite(v)&&v>0);const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;const median=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),i=Math.floor(b.length/2);return b.length%2?b[i]:(b[i-1]+b[i])/2};return{fuelMedian:median(economies),fuelAvg:avg(economies),tripAvg:avg(dist),tripCount:trips.length,monthlySpend:avg(costs),fuelSamples:economies.length,maintenanceCount:maintenanceRows.length}}
async function renderMemory(){const r=await memory();const target=document.getElementById('vehicleMemory');if(!target)return;const card=(label,value,note)=>`<article class="memory-card"><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`;target.innerHTML=`<div class="panel-header"><div><span class="eyebrow">LEARNING FROM YOUR DATA</span><h2>YOUR NORMAL</h2></div><span class="briefing-confidence">${r.fuelSamples+r.tripCount>8?'LEARNING':'BUILDING'}</span></div><div class="memory-grid">${card('NORMAL FUEL',r.fuelMedian?`${r.fuelMedian.toFixed(1)} L/100 km`:'—',r.fuelSamples>=3?'Personal median economy':'Log 3+ fuel records')} ${card('TYPICAL DRIVE',r.tripAvg?`${r.tripAvg.toFixed(1)} km`:'—',r.tripCount>=3?'Average recorded trip':'Record more drives')} ${card('SERVICE HISTORY',String(r.maintenanceCount),r.maintenanceCount?'Records stored locally':'Add your first service')} ${card('DATA CONFIDENCE',`${Math.min(100,Math.round((r.fuelSamples*12+r.tripCount*6+r.maintenanceCount*8)))}%`,r.fuelSamples>=3&&r.tripCount>=3?'Enough to spot personal patterns':'More history improves this')}</div><p class="memory-note">DRIVE uses your own history as the reference point. As the dataset grows, alerts can compare today against what is normal for your car and your driving.</p>`}
function mountMemory(){let d=document.getElementById('vehicleMemory');if(!d){const brief=document.getElementById('driveBriefing');if(!brief)return;d=document.createElement('section');d.id='vehicleMemory';d.className='panel vehicle-memory';brief.insertAdjacentElement('afterend',d)}renderMemory()}
window.DRIVE_MEMORY={analyse:memory,refresh:renderMemory};
document.addEventListener('DOMContentLoaded',()=>{more();mountMemory();window.addEventListener('drive:datachanged',()=>{renderMemory();renderDocuments?.(document.getElementById('documentsModal'))})});
})();
